# Generated by Django 3.2.16 on 2024-06-02 23:55

from django.db import migrations, models
import mail_glint.apps.users.models.index


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='작가소개'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=mail_glint.apps.users.models.index.image_path),
        ),
    ]
