# Generated by Django 3.2.16 on 2024-05-27 16:02

from django.db import migrations, models
import django.utils.timezone
import mail_glint.apps.subscribers.models.index
import mail_glint.bases.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('language', models.TextField(blank=True, choices=[('en', 'English'), ('ko', 'Korean'), ('cn', 'Chinese'), ('vn', 'Vietnam'), ('ru', 'Russian')], null=True, verbose_name='language')),
                ('send_count', models.IntegerField(default=0, verbose_name='count')),
            ],
            options={
                'verbose_name': '구독자',
                'verbose_name_plural': '구독자',
                'db_table': 'subscribers',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriberAuthentication',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=mail_glint.apps.subscribers.models.index.get_expiration_time)),
            ],
            options={
                'verbose_name': '구독자 인증',
                'verbose_name_plural': '구독자 인증',
                'db_table': 'subscriber_authentications',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
    ]
