# Generated by Django 3.2.16 on 2024-05-27 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mail_glint.apps.articles.models.index
import mail_glint.apps.articles.models.mixins.article
import mail_glint.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('title', models.TextField(verbose_name='제목')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='부제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('thumbnail', models.ImageField(upload_to=mail_glint.apps.articles.models.mixins.article.image_path)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사',
                'db_table': 'articles',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.TextField(unique=True, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '기사 카테고리',
                'verbose_name_plural': '기사 카테고리',
                'db_table': 'article_categories',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.TextField(unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '기사 태그',
                'verbose_name_plural': '기사 태그',
                'db_table': 'article_tags',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HumanArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('title', models.TextField(verbose_name='제목')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='부제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('thumbnail', models.ImageField(upload_to=mail_glint.apps.articles.models.mixins.article.image_path)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '인물 기사',
                'verbose_name_plural': '인물 기사',
                'db_table': 'human_articles',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('number', models.PositiveIntegerField(verbose_name='에피소드 넘버')),
                ('name', models.TextField(unique=True, verbose_name='에피소드 명')),
                ('thumbnail', models.ImageField(null=True, upload_to=mail_glint.apps.articles.models.index.image_path)),
                ('human_articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='articles.humanarticle')),
            ],
            options={
                'verbose_name': '인물기사 에피소드',
                'verbose_name_plural': '인물기사 에피소드',
                'db_table': 'episodes',
                'ordering': ['-created'],
            },
            bases=(mail_glint.bases.models.UpdateMixin, models.Model),
        ),
    ]
