# Generated by Django 3.2.16 on 2024-06-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_episode_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='부제목'),
        ),
    ]
