# Generated by Django 3.2.16 on 2024-06-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_episode_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanarticle',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='인물 이름'),
        ),
    ]
