# Generated by Django 3.2.16 on 2024-06-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_humanarticle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='humanarticle',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
    ]
